import fs from "node:fs"

import { describe, expect, it } from "vitest"

describe("public check page scaffolding", () => {
  it("adds a public check entry to the homepage header and removes the admin security nav item", () => {
    const publicHeader = fs.readFileSync("apps/web/components/public-header.tsx", "utf8")
    const adminNav = fs.readFileSync("apps/web/components/admin/admin-nav.tsx", "utf8")
    const routePath = "apps/web/app/[lang]/check/page.tsx"

    expect(publicHeader).toContain('{ label: "Check"')
    expect(publicHeader).toContain('item.surface === "check"')
    expect(publicHeader).toContain('route: "/check"')
    expect(adminNav).not.toContain('href: "/admin/security"')
    expect(fs.existsSync(routePath)).toBe(true)
  })

  it("renders the public check page with the shared header and package-check workbench", () => {
    const route = fs.readFileSync("apps/web/app/[lang]/check/page.tsx", "utf8")
    const componentPath = "apps/web/components/security/package-check-workbench.tsx"

    expect(fs.existsSync(componentPath)).toBe(true)

    const component = fs.readFileSync(componentPath, "utf8")

    expect(route).toContain("PublicHeader")
    expect(route).toContain("PackageCheckWorkbench")
    expect(route).toContain("PackageCheckWorkbench")
    expect(route).toContain("lang={lang}")
    expect(route).toContain("initialOverviewTotals={overviewTotals}")
    expect(route).not.toContain("publicCheckTitle")
    expect(route).not.toContain("publicCheckDescription")
    expect(component).toContain('fetch("/api/security/check/packages"')
    expect(component).toContain("buildSecurityCheckRequestBody")
    expect(component).toContain("parseSecurityCheckPayload")
    expect(component).toContain("setResult(null)")
    expect(component).toContain("publicCheckSubmit")
    expect(component).toContain("publicCheckSubmitting")
    expect(component).toContain("publicCheckSearchHint")
    expect(component).toContain("publicCheckOverviewBadge")
    expect(component).toContain("publicCheckMatchCountBadge")
    expect(component).toContain("publicCheckHitCountBadge")
    expect(component).toContain("const findingsPerPage = 3")
    expect(component).toContain("currentPage")
    expect(component).toContain("slice(pageStart, pageEnd)")
    expect(component).toContain("Math.ceil(result.findings.length / findingsPerPage)")
    expect(component).toContain("publicCheckResultLabel")
    expect(component).toContain("publicCheckSummaryLabel")
    expect(component).toContain("publicCheckDetailsLabel")
    expect(component).toContain("publicCheckDetailsToggle")
    expect(component).toContain("publicCheckDetailsCollapse")
    expect(component).toContain("ChevronRight")
    expect(component).toContain("ChevronDown")
    expect(component).toContain("items-center justify-between")
    expect(component).toContain("publicCheckAffectedVersionsLabel")
    expect(component).toContain("publicCheckAffectedRangesLabel")
    expect(component).toContain("publicCheckNoFindings")
    expect(component).toContain("finding.advisory.summary")
    expect(component).toContain("finding.advisory.details")
    expect(component).toContain("MarkdownSummary")
    expect(component).toContain("MarkdownRenderer")
    expect(component).toContain("buildSummaryPreviewText")
    expect(component).toContain("line-clamp-2")
    expect(component).toContain("finding.matchSummary")
    expect(component).toContain("finding.matchReason")
    expect(component).toContain("finding.confidence")
    expect(component).toContain("finding.affectedPackage.affectedVersions")
    expect(component).toContain("formatAffectedRanges")
    expect(component).toContain("finding.affectedPackage.fixedVersions")
    expect(component).toContain("finding.advisory.references")
    expect(component).toContain('rounded-[1.35rem] border border-black/5 bg-white/70 p-3')
    expect(component).toContain('type="search"')
    expect(component).toContain("Search className")
    expect(component).toContain("buttonVariants")
    expect(component).toContain("resetSearchState")
    expect(component).toContain('setPackageName("")')
    expect(component).toContain('setVersion("")')
    expect(component).toContain('setResult(null)')
    expect(component).toContain("selectOpen")
    expect(component).toContain("role=\"listbox\"")
    expect(component).toContain("aria-haspopup=\"listbox\"")
    expect(component).toContain("lg:w-[208px]")
    expect(component).not.toContain("getAdminSelectClassName")
    expect(component).not.toContain("<select")
    expect(component).not.toContain("<Card>")
    expect(component).not.toContain("publicCheckEmpty")
    expect(component).not.toContain('<li key={reference.url}')
  })

  it("adds public-facing copy for result sections without a long query explainer", () => {
    const copy = fs.readFileSync("apps/web/lib/i18n.ts", "utf8")

    expect(copy).not.toContain('publicCheckTitle: "包查询"')
    expect(copy).not.toContain('publicCheckDescription: "选择生态并输入包名即可查询。填写版本号时会返回更细的命中结果。"')
    expect(copy).toContain('publicCheckSearchHint: "搜索你想查询的软件包，填写版本可获得更精确结果。"')
    expect(copy).toContain("publicCheckOverviewBadge:")
    expect(copy).toContain("publicCheckMatchCountBadge:")
    expect(copy).toContain("publicCheckHitCountBadge:")
    expect(copy).toContain("publicCheckPageStatus:")
    expect(copy).toContain('publicCheckResultLabel: "查询结果"')
    expect(copy).toContain('publicCheckSummaryLabel: "简短说明"')
    expect(copy).toContain('publicCheckDetailsLabel: "详细说明"')
    expect(copy).toContain('publicCheckDetailsToggle: "展开详细说明"')
    expect(copy).toContain('publicCheckDetailsCollapse: "收起详细说明"')
    expect(copy).toContain('publicCheckAffectedVersionsLabel: "受影响版本"')
    expect(copy).toContain('publicCheckAffectedRangesLabel: "受影响范围"')
    expect(copy).not.toContain('publicCheckTitle: "Package check"')
    expect(copy).not.toContain('publicCheckDescription:')
    expect(copy).toContain('publicCheckSearchHint: "Search the package you want to check. Add a version for a more precise result."')
    expect(copy).toContain("publicCheckOverviewBadge:")
    expect(copy).toContain("publicCheckMatchCountBadge:")
    expect(copy).toContain("publicCheckHitCountBadge:")
    expect(copy).toContain("publicCheckPageStatus:")
    expect(copy).toContain('publicCheckResultLabel: "Result"')
    expect(copy).toContain('publicCheckSummaryLabel: "Summary"')
    expect(copy).toContain('publicCheckDetailsLabel: "Details"')
    expect(copy).toContain('publicCheckDetailsToggle: "Expand full details"')
    expect(copy).toContain('publicCheckDetailsCollapse: "Collapse full details"')
    expect(copy).toContain('publicCheckAffectedVersionsLabel: "Affected versions"')
    expect(copy).toContain('publicCheckAffectedRangesLabel: "Affected ranges"')
    expect(copy).not.toContain('publicCheckFootnote:')
  })
})
